BT_GATT_SERVICE_DEFINE(my_svc,
    BT_GATT_PRIMARY_SERVICE(BT_UUID_DECLARE_128(...)),

    BT_GATT_CHARACTERISTIC(
        BT_UUID_DECLARE_128(...),
        BT_GATT_CHRC_NOTIFY,
        BT_GATT_PERM_NONE,
        NULL, NULL, NULL
    ),
);